apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pink-app
  namespace: argocd
spec:
  project: my-project
  source:
    repoURL: https://github.com/LizaSaitov/GitOps.git
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

